services:
  backend-java:
    build: ./backend-java
    profiles: ["java"]
    expose:
      - "8080"
    networks:
      default:
        aliases:
          - backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  backend-kotlin:
    build: ./backend-kotlin
    profiles: ["kotlin"]
    expose:
      - "8080"
    networks:
      default:
        aliases:
          - backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  backend-python:
    build: ./backend-python
    profiles: ["python"]
    expose:
      - "8080"
    networks:
      default:
        aliases:
          - backend

  backend-rust:
    build: ./backend-rust
    profiles: ["rust"]
    expose:
      - "8080"
    networks:
      default:
        aliases:
          - backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
